#customeradmin
INSERT INTO `customeradmin` VALUES (5001, 'Mary', 'Johns', 'mj1234@temp.com', 'mjohn1111', 0);
INSERT INTO `customeradmin` VALUES (5002, 'Patrick', 'Park', 'ParkP@mytudubli.ie', 'pass0000', 0);
INSERT INTO `customeradmin` VALUES (0001, 'Dain', 'Kim', 'dkim@example.com', 'admin1234', 1);

#product
INSERT INTO `product` VALUES(1001, 'White Loose T-shirt', 'tops','t-shirt','white',30.00,10,'Image by <a href="https://pixabay.com/users/melancholiaphotography-2312503/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1462985">melancholiaphotography</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1462985">Pixabay</a>');
INSERT INTO `product` VALUES(1003, 'Yellow Hoodies','tops','hoodies','yellow',32.00, 10, 'Image by <a href="https://pixabay.com/users/Erik_Lucatero-8817894/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3353711">Erik Lucatero</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3353711">Pixabay</a>');
INSERT INTO `product` VALUES(1004,'Strip T-shirt','tops','t-shirt','white',35.00,10,'Image by <a href="https://pixabay.com/users/Pexels-2286921/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1284460">Pexels</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1284460">Pixabay</a>');
INSERT INTO `product` VALUES(1005,'USA T-shirt','tops','t-shirt','grey',34.00, 10, 'Image by <a href="https://pixabay.com/photos/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=918417">Free-Photos</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=918417">Pixabay</a>');
INSERT INTO `product` VALUES(1006, 'Floral Lace Dress' , 'dresses' ,'long','purple', 99.99, 10, 'Image by <a href="https://pixabay.com/users/N-Y-C-8156946/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3179178">N-Y-C</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3179178">Pixabay</a>');
INSERT INTO `product` VALUES(1007, 'Floral Black Blouse', 'tops' , 'blouse', 'black', 40.00, 10, 'Image by <a href="https://pixabay.com/users/SnapwireSnaps-692569/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=597173">SnapwireSnaps</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=597173">Pixabay</a>');
INSERT INTO `product` VALUES(1008, 'Armani Leather Jacket','outerwears','jacket','black',85.00, 10, 'Image by <a href="https://pixabay.com/users/Pexels-2286921/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1866572">Pexels</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1866572">Pixabay</a>');
INSERT INTO `product` VALUES(1009, 'Pink Wave Dress', 'dresses','short','pink',72.00, 10, 'Image by <a href="https://pixabay.com/users/nastya_gepp-3773230/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3075704">Анастасия Гепп</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3075704">Pixabay</a>');
INSERT INTO `product` VALUES(1010, 'White Hoodies', 'tops','hoodies','white',40.00,10, 'Image by <a href="https://pixabay.com/users/StockSnap-894430/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2568524">StockSnap</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2568524">Pixabay</a>');
INSERT INTO `product` VALUES(1011, 'Simple Leather Jacket' ,'outerwears','jacket','black',75.00,10,'Image by <a href="https://pixabay.com/users/nastya_gepp-3773230/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3083402">Анастасия Гепп</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3083402">Pixabay</a>');
INSERT INTO `product` VALUES(1012, 'Blue Denim Jacket','outerwears','jacket','black', 45.00, 10, 'Image by <a href="https://pixabay.com/photos/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=731258">Free-Photos</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=731258">Pixabay</a>');
INSERT INTO `product` VALUES(1013, 'Shoulder Strap Dress','dresses','short','brown',65.00,10, 'Image by <a href="https://pixabay.com/users/ptksgc-4666965/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2099363">Pham Trung Kien</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2099363">Pixabay</a>');
INSERT INTO `product` VALUES(1014, 'Backstitch Knit Dress','dresses','short','white',75.00, 10, 'Image by <a href="https://pixabay.com/users/polocanon7d-2422200/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1338994">polocanon7d</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1338994">Pixabay</a>');
INSERT INTO `product` VALUES(1015, 'Shoulder Hole T-shirt','tops','t-shirt','beige',25.00, 10, 'Image by <a href="https://pixabay.com/users/3179289-3179289/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1623088">3179289</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1623088">Pixabay</a>');
INSERT INTO `product` VALUES(1016, 'Black Lace Shirt','tops','shirt','black',55.00,10, 'Image by <a href="https://pixabay.com/users/3179289-3179289/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1623090">3179289</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1623090">Pixabay</a>');
INSERT INTO `product` VALUES(1017, 'Off Shoulder Shirt','tops','shirt','white',45.00, 10, 'Image by <a href="https://pixabay.com/users/3179289-3179289/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1623086">3179289</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1623086">Pixabay</a>');
INSERT INTO `product` VALUES(1018, 'Ribbon Blouse','tops','shirt','white',65.00,10,'Image by <a href="https://pixabay.com/users/polocanon7d-2422200/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1338993">polocanon7d</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1338993">Pixabay</a>');
INSERT INTO `product` VALUES(1019, 'Ripped Jeans','bottoms','jeans','blue',35.00, 10, 'Image by <a href="https://pixabay.com/photos/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1245922">Free-Photos</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1245922">Pixabay</a>');
INSERT INTO `product` VALUES(1020, 'Navy Silk Dress','dresses','long','navy',80.00, 10,'Image by <a href="https://pixabay.com/users/Alpcem-13834806/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=4613470">Alp Cem</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=4613470">Pixabay</a>');
INSERT INTO `product` VALUES(1021, 'White Knit Dress','dresses','short','white',65.00, 10, 'Image by <a href="https://pixabay.com/photos/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1208325">Free-Photos</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1208325">Pixabay</a>');
INSERT INTO `product` VALUES(1022, 'Bright Jeans','bottoms','jeans','blue',45.00, 10, 'Image by <a href="https://pixabay.com/photos/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1031306">Free-Photos</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1031306">Pixabay</a>');
INSERT INTO `product` VALUES(1023, 'No One Cares Jeans','bottoms','jeans','blue',35.00, 10, 'Image by <a href="https://pixabay.com/users/milivanily-742747/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1234687">Milada Vigerova</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1234687">Pixabay</a>');
INSERT INTO `product` VALUES(1024, 'White Lace Blouse','tops' , 'blouse','white', 50.00, 10, 'Image by <a href="https://pixabay.com/users/nastya_gepp-3773230/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3075710">Анастасия Гепп</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3075710">Pixabay</a>');
INSERT INTO `product` VALUES(1025, 'Leather Skrit','bottoms','skirt','black',60.00, 10, 'Image by <a href="https://pixabay.com/users/Tudor44-2864748/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1600357">Tudor George</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1600357">Pixabay</a>');
INSERT INTO `product` VALUES(1026, 'Black Leather Skirt','bottoms','skirt','black',40.00, 10,'Image by <a href="https://pixabay.com/users/Victoria_Borodinova-6314823/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3683184">Виктория Бородинова</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3683184">Pixabay</a>');
INSERT INTO `product` VALUES(1027, 'Sparkling Skirt', 'bottoms','skirt','grey', 45.00, 10, 'Image by <a href="https://pixabay.com/users/aproman-1595112/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1366433">jongbok kim</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1366433">Pixabay</a>');
INSERT INTO `product` VALUES(1028, 'Floral Skirt', 'bottoms','skirt','black',40.00, 10,'Image by <a href="https://pixabay.com/users/aproman-1595112/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1366433">jongbok kim</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1366433">Pixabay</a>');
INSERT INTO `product` VALUES(1030, 'Black Fur Coat','outerwears','coat','black',120.00, 10, 'Image by <a href="https://pixabay.com/users/JillWellington-334088/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=635271">Jill Wellington</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=635271">Pixabay</a>');
INSERT INTO `product` VALUES(1031, 'Blue Coat','outerwears','coat','blue',60.00, 10,'Image by <a href="https://pixabay.com/users/VladBitte-2651064/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2865604">Vlad Bitte</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2865604">Pixabay</a>');
INSERT INTO `product` VALUES(1032, 'Pink Coat','outerwears','coat','pink',70.00, 10,'Image by <a href="https://pixabay.com/users/StockSnap-894430/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2589812">StockSnap</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2589812">Pixabay</a>');
INSERT INTO `product` VALUES(1034, 'White Belt Coat','outerwears','coat','white',70.00, 10,'Image by <a href="https://pixabay.com/users/beegaia-3888548/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2662927">beegaia</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2662927">Pixabay</a>');
#cart
INSERT INTO `cart`(`c_id`, `p_id`, `c_quantity`) VALUES (5001, 1001, 1);
INSERT INTO `cart`(`c_id`, `p_id`, `c_quantity`) VALUES (5001, 1006, 2);
INSERT INTO `cart`(`c_id`, `p_id`, `c_quantity`) VALUES (5002, 1004, 5);